# Changes here will be overwritten by Copier
SelectCitation: []
SelectCodeQualityFeatures:
- AddLocalTests_flag
- SelectGitHubActions_flag
- AddLinting_flag
- AddPreCommit_flag
SelectCommunityFeatures: []
SelectDocumentationFeatures: []
SelectGitHubActions:
- AddGitHubActionBuild_flag
- AddLinkCheck_flag
SelectPublishReleaseFeatures:
- SelectCitation_flag
- AddChangeLog_flag
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Flavio Hafner
email: hafner.flavio@gmail.com
full_name: Flavio Hafner
github_organization: f-hafner
keywords: pytorch, transformer, distributed-training
license: Apachev2
package_name: mintransformer
package_short_description: DDP for transformer models
template_profile: ask
version: 0.1.0
